name: emirs-bank-v2
region: nyc
domains:
  - domain: www.emirs-banking.com
    type: PRIMARY
  - domain: emirs-banking.com
    type: ALIAS
static_sites:
  - name: website
    source_dir: /
    output_dir: /
    index_document: index.html
    error_document: 404.html
    environment_slug: html
    github:
      branch: main
      repo: alyssakulani8-cell/emirs-bank
      deploy_on_push: true
